### ISSUE TITLE
config上的ALIPAY_API_LIST的问题

### ISSUE THREAD

**Issue by liqingfeng** [Luncher/alipay#10]
ALIPAY_API_LIST只有'alipay.trade.query'和'alipay.trade.app.pay'，我在做退款申请的时候在makeResponse中respType会是undefined，导致response[respType]时会报错Cannot read property 'code' of undefined，这里是不是有问题？？

**Comment by Luncher** [comment]
可能是一个BUG，周末有时间我看看

**Comment by Luncher** [comment]
问题修复了 请升级到v2.2
