### ISSUE TITLE
同步通知结果校验,看了代码没看到校验签名

### ISSUE THREAD

**Issue by dovewi** [Luncher/alipay#12]
感觉很不安,为什么只有异步通知校验了签名

**Comment by HobaiRiku** [comment]
由于同步通知和异步通知都可以作为支付完成的凭证，且异步通知支付宝一定会确保发送给商户服务端。为了简化集成流程，商户可以将同步结果仅仅作为一个支付结束的通知（忽略执行校验），实际支付是否成功，完全依赖服务端异步通知。
