### ISSUE TITLE
app支付后，verifyPayment同步校验一直不过

### ISSUE THREAD

**Issue by liqingfeng** [Luncher/alipay#13]
app支付成功支付宝返回的url传给后台解析出的result为"{"alipay_trade_app_pay_response":{"code":"10000","msg":"Success",。。。}"
报错为
"Cannot use 'in' operator to search for 'alipay_trade_query_response' in {"alipay_trade_app_pay_response":{"code":"10000","msg":"Success",。。。。}"
这里是不是少了什么？

**Comment by liqingfeng** [comment]
我发现是在这个函数里
function responseType(response) {
  var type = Object.keys(_config2.default.ALIPAY_API_LIST).map(function (name) {
    return name.replace(/\./g, '_');
  }).find(function (api) {
    return api + '_response' in response;
  });
  if (type) return type + '_response';
}
由于传进去的response是一个字符串，当用in操作时报错的，所以这个verifyPayment函数传进去的参数result具体应该是什么格式？

**Comment by iyjian** [comment]
@liqingfeng 是不是要用body parser 弄成Obj的

**Comment by liqingfeng** [comment]
@iyjian 我在这个项目的源代码里，在verifyPayment里把参数做了个JSON.parse，这样就能校验过了。不过我不知道这样改是否会引入其它问题。
