### ISSUE TITLE
queryOrder 订单查询接口，一直返回‘交易不存在’？

### ISSUE THREAD

**Issue by wangzhilongh** [Luncher/alipay#14]
我创建订单没问题，,"out_trade_no":"117814570259111501"用这个订单号创建的，可以正常打开支付。但一直查询结果时，一样用这个out_trade_no，一直返回‘交易不存在’？

{"code":"-1","data":{"code":"40004","msg":"Business Failed","sub_code":"ACQ.TRADE_NOT_EXIST","sub_msg":"交易不存在","buyer_pay_amount":"0.00","invoice_amount":"0.00","out_trade_no":"117814570259111501","point_amount":"0.00","receipt_amount":"0.00"},"message":"error"}

**Comment by Luncher** [comment]
@wangzhilongh  问题还存在吗？

**Comment by wangzhilongh** [comment]
没事了，我查询已经支付成功的订单是可以正常返回的。但查询未支付的，还是一直返回‘交易不存在’。
功能可以凑合用，就是返回‘交易不存在’，感觉有误导，让人觉得自己传递的订单号不对。。。。坑了我2个多小时。
不过还是非常感谢哈，最近用egg做项目，希望能多和大神学习交流哈！

**Comment by Luncher** [comment]
别客气，有问题随时可以找我。
