### ISSUE TITLE
接口返回码 `code` 参数的类型不统一

### ISSUE THREAD

**Issue by rrbe** [Luncher/alipay#16]
定义上说接口返回是统一的
```
{
    "code": string,
    "message": string,
    "data": string
}
```

实际使用的时候，发现其中的 `code` 参数在有些接口如 `createAppOrder`, `createPageOrder` 等是`number` 类型，在其他接口是 `string`

看代码发现是这样的。建议把错误码改成常量然后用到的时候用常量就好，这样会不会好一点？

希望如果有空能修改一下，非常感谢啦~

**Comment by Luncher** [comment]
好的，这个可能要周末放假才有空修改了，感谢你的建议 ：）

**Comment by rrbe** [comment]
如果忙的话，要么我改一下提个 pr 吧？
就类似 ./src/config/api.js ，加一个 /config/api_code.js, 里面类似这样
`javascript
export const CODE = {
    'SUCCESS': '0',
    'PROCESSING': '1'
    ...
}
`
然后在 index.js 里做替换，`'0' -> CODE.SUCCESS`这样虽然写得多了，但是有 ide 提示也不会错，也不会因为少写了引号出错

**Comment by Luncher** [comment]
你提一个pr吧！ @rrbe

**Comment by rrbe** [comment]
#19 
 Hi，能否看一下有什么问题，可以提出来再改~

**Comment by Luncher** [comment]
@rrbe 能再看一下嘛，我把项目重构了～
