### ISSUE TITLE
sign(privateKey, ...) 报 PEM_read_bio_PrivateKey failed

### ISSUE THREAD

**Issue by xfcdxg** [Luncher/alipay#17]
nodejs: v8.9.4

alipay-mobile: v2.2.1

我用你项目中测试用例里的 app_priv_key.pem 也会报这个错。

麻烦看看呗，是啥问题导致的呢？

**Comment by Luncher** [comment]
@xfcdxg 问题解决了吗？

**Comment by xfcdxg** [comment]
@Luncher 我重新生成了一组公私钥，就可以了...

**Comment by Luncher** [comment]
之前我用过支付宝的工具，确认是可以用的。支付宝推荐的加密算法是AES256。

**Comment by xfcdxg** [comment]
@Luncher 与系统有关系吗？我用的是MacOS

**Comment by Luncher** [comment]
不确定，之前用的fedora试的，回头我在mac试一下。

**Comment by jinhedev** [comment]
我遇到了同一个问题： ·PEM_read_bio_PrivateKey failed·
我的公私钥是用支付宝提供的工具生成的。我的操作环境是macOS。

**Comment by Luncher** [comment]
能不能Debug看一下，把错误信息贴一下，我现在手头没有对应的项目。
