### ISSUE TITLE
异步回调地址与返回url问题

### ISSUE THREAD

**Issue by sfyr111** [Luncher/alipay#18]
const basicParams = {
  return_url: 'http://xxx.com'
}
这里的return_url是支付后返回的url链接吗？
为啥没有notify_url回调响应配置？

**Comment by Luncher** [comment]
notify_url 是什么链接地址？ @sfyr111

**Comment by sfyr111** [comment]
notify_url应该是回调通知地址。文档里有这个参数  @Luncher

**Comment by sfyr111** [comment]
服务端不是要配一个post地址接受支付宝支付成功后的回调结果吗

**Comment by Luncher** [comment]
我看了下实现， `notify_url`是有支持的，你用吧！有问题再找我哈 ：）
