### ISSUE TITLE
能不能做个单笔付款到支付宝的接口非常感谢!

### ISSUE THREAD

**Issue by issmile** [Luncher/alipay#2]
能不能做个单笔付款到支付宝的接口非常感谢!

**Comment by Luncher** [comment]
@issmile  什么功能？有没有文档发给我看看。

**Comment by zengleyi** [comment]
https://docs.open.alipay.com/api_28/alipay.fund.trans.toaccount.transfer/
这是支付宝官方的文档@Luncher

**Comment by Luncher** [comment]
@zengleyi @issmile 接口做好了
