### ISSUE TITLE
可以把我添加到成员里面吗?

### ISSUE THREAD

**Issue by daiyunchao** [Luncher/alipay#23]
我实现了alipay.fund.trans.order.query(查询转账订单接口) 可以添加成员,并且提交代码吗,

**Comment by Luncher** [comment]
这个接口原来不是已经有了么？你指的是？

**Comment by Luncher** [comment]
你提一个merge request吧

**Comment by daiyunchao** [comment]
嗯 有的是 查询订单,但alipay.fund.trans.order.query(查询转账订单接口) 是查询 提现到支付宝的的时候查询的 文档地址:https://docs.open.alipay.com/api_28/alipay.fund.trans.order.query/ 不适用于:通用查询订单

**Comment by daiyunchao** [comment]
我已经添加了 pull request

**Comment by daiyunchao** [comment]
可以看到我提交的 request吗? 是有啥问题吗

**Comment by Luncher** [comment]
尽量不要去修改跟你描述的功能不相干的代码。

**Comment by daiyunchao** [comment]
木有改啊,可能是我习惯性格式化导致的...

**Comment by daiyunchao** [comment]
是有什么问题吗? 不能合并?
