### ISSUE TITLE
请问如何设置为沙箱测试模式？

### ISSUE THREAD

**Issue by 383366204** [Luncher/alipay#26]
我写了process.env.NODE_ENV = ‘test’，支付宝的页面显示“错误代码 invalid-signature 错误原因: 验签出错，sign参数值非法，请检查是否做了正确的url编码”，是不是哪里错了

**Comment by Luncher** [comment]
沙箱模式就是把账号密码配置成一个测试号，其它配置可能也要相应的变更。
