### ISSUE TITLE
请问notfiy_url能否单独设置？

### ISSUE THREAD

**Issue by zhuozhongcao** [Luncher/alipay#29]
现在似乎只有Alipay对象初始化的时候才会生效，之后每个请求单独设置不生效的

**Comment by zhuozhongcao** [comment]
createPageOrderURL这个方法好像notify_url完全不生效诶 能否加一下

**Comment by Luncher** [comment]
为什么需要每个请求通知url不一致呢？

**Comment by zhuozhongcao** [comment]
因为业务逻辑不一样。不过这个问题自己封装一下也能解决，但是createPageOrderURL这个方法notify_url无效就比较麻烦了，能看一下吗

**Comment by Luncher** [comment]
`createPageOrderURL`函数需要两个参数, notify_url应该放在第二个参数对象里面。

**Comment by zhuozhongcao** [comment]
我自己写错了，不好意思，确实是生效的
