### ISSUE TITLE
makeNotifyResponse 返回结果一直是 -2

### ISSUE THREAD

**Issue by zuijiaoluo** [Luncher/alipay#31]
```
{ code: '-2',
message: 'permission denied'
...}
```

**Comment by Luncher** [comment]
DEBUG信息看一下，是不是配置信息没有对？

**Comment by zuijiaoluo** [comment]
配置应该是对的，可以创建订单
返回结果认证代码
```
   const result = await service.makeNotifyResponse(req.body);
```
配置代码
```
const options = {
  app_id: app_id,
  appPrivKeyFile: read('./xxx.pem'),
  alipayPubKeyFile: read('./xxx.pem'),
};
const service = new Alipay(options);
```

**Comment by Luncher** [comment]
根据[文档](https://docs.open.alipay.com/204/105301/)，**支付宝是用POST方式发送通知信息，因此该页面中获取参数的方式，如：request.Form(“out_trade_no”)、$_POST[‘out_trade_no’]；**。你直接把req.body传递进去了。你看看是不是这里出了问题。

**Comment by zuijiaoluo** [comment]
我在 req.body 中拿到了  out_trade_no、trade_no  等等参数，调用 makeNotifyResponse是否是把这些参数全部传入还是只传入部分需要的，
```
支付宝是用POST方式发送通知信息，因此该页面中获取参数的方式，如：request.Form(“out_trade_no”)、$_POST[‘out_trade_no’]； 
```
这个感觉是其他语言的写法，用 express  获取 body 内容应该是 req.body

**Comment by Luncher** [comment]
你说的没错，仔细看了下确实应该把整个数据都传入的，那只能看一下调试信息了，你把支付宝通知的信息保存下来，手动调用一次makeNotifyResponse试一下。`-2`是我们sdk返回的错误码，你得看看支付宝返回的错误信息是什么。

**Comment by Luncher** [comment]
@zuijiaoluo 有结果了嘛？

**Comment by Luncher** [comment]
@zuijiaoluo 不知道你是不是一样的情况呢？

**Comment by Luncher** [comment]
传入的参数应该是自己的私钥加上支付宝的公钥。

**Comment by Eden-Harris** [comment]
@zuijiaoluo @Luncher 这个问题我也遇到了, 不知道你们解决了没有。
使用的是 appPrivKeyFile：app_priv_key.pem + alipayPubKeyFile：alipay_public_key.pem ；既然支付都能成功支付了，说明应该不是证书的问题吧
```bash
{ code: '-2',
  message: 'permission denied',
  data:
   { gmt_create: '2018-07-04 16:51:58',
     charset: 'utf-8',
```

**Comment by Luncher** [comment]
@Eden-Harris @cloudfreexiao @zuijiaoluo 能不能帮我看一下你的私钥文件是以：`BEGIN RSA PRIVATE` 开头 还是以`BEGIN PRIVATE KEY`开头的。

**Comment by Eden-Harris** [comment]
@Luncher 我现在用的是新版的支付宝，没有 -----BEGIN PRIVATE KEY----- 之类的
![image](https://user-images.githubusercontent.com/28903167/42303886-01f7e178-8056-11e8-8f63-be47ab98bbda.png)
以下是引用代码 （options里面的notify_url参数在使用说明里面没有，是我自己试出来的，Luncher 你忘了写这个参数到说明里了）
![image](https://user-images.githubusercontent.com/28903167/42303964-613f79ac-8056-11e8-8c4c-8b6d6895d4e5.png)
以下是我以前老代码支付宝配置截图
![image](https://user-images.githubusercontent.com/28903167/42304096-217cc3d2-8057-11e8-8f46-2211784c87dc.png)

**Comment by cloudfreexiao** [comment]
@Luncher  我的是用 阿里工具直接生成的 没有 BEGIN 我看代码里有 自己添加 这些 解析的 就没动
支付宝 回调验签 要用 支付宝的公钥 不能用 自己生成上传 我解决这个问题 就是这样搞定的

**Comment by Luncher** [comment]
@Eden-Harris 我以为你们会去看看文档，参数比较多，我没有一一列出来：）

**Comment by Luncher** [comment]
@Eden-Harris 文档加好了～

**Comment by cloudfreexiao** [comment]
好的
