### ISSUE TITLE
在支付宝异步通知时获取到的参数为空

### ISSUE THREAD

**Issue by cloudfreexiao** [Luncher/alipay#33]
在支付宝异步通知时获取到的参数为空 使用express模块
请问 有遇到过吗
初步 怀疑是 支付宝 数据 不是规范数据？

**Comment by Luncher** [comment]
加下日志，看看返回的是什么，不要怀疑：）

**Comment by cloudfreexiao** [comment]
按这个方法 可以收到了
[回调参数](https://segmentfault.com/q/1010000004122789)
但是 发现 遇到了 这个一样的问题 [issue](https://github.com/Luncher/alipay/issues/31)
