### ISSUE TITLE
异步回调问题

### ISSUE THREAD

**Issue by azayu** [Luncher/alipay#37]
拿到支付宝异步回调的报文，直接用verifyPayment 怎么验证不成功？返回错误 code:-1  message:error

**Comment by Luncher** [comment]
错误信息可以贴一下吗？

**Comment by azayu** [comment]
1.同步的错误消息
{
 "memo": "",
"resultStatus": "9000",
 "result":{..}
}
直接调用返回"result. Length equal 0."

如果把result 当字符串传如：
{
 "memo": "",
"resultStatus": "9000",
 "result":"{\"alipay_trade_app_pay_response\": 
       {\"code\":\"10000\",\"msg\":\"Success\",\"app_id\":\"2018102561774974\",\"auth_app_id\":\"201.
      ..."
}
会返回
：message:"Cannot use 'in' operator to search for 'alipay_trade_query_response' in {"alipay_trade_app_pay_response":{"code":"10000","msg":"Success ...

看了你里面验证的结构  是使用&组成字符串验证 
 
同步验证  是使用json格式
异步验签 才是用&

**Comment by Luncher** [comment]
@azayu 我不太明白你说的意思，我把项目重构了，你有空帮我看一下，还会不会出现你说的这个问题～
