### ISSUE TITLE
订单查询报错 Cannot read property \'code\' of undefined',

### ISSUE THREAD

**Issue by sandywk** [Luncher/alipay#38]
NodeJS代码
const service = new Alipay(options)  //配置没有问题生成支付链接都可以
console.log(out_trade_no) //订单号也没有问题
const verify = await service.queryOrder({ out_trade_no });
console.log(verify)
报错信息
{ code: '-1',message: 'Cannot read property \'code\' of undefined',data: {} }

这个报错没看懂，求帮助。

**Comment by sandywk** [comment]
@Luncher 有空的时候帮忙看看 多谢

**Comment by sandywk** [comment]
版本 "alipay-mobile": "^2.2.7"

**Comment by sandywk** [comment]
@Luncher

**Comment by Luncher** [comment]
@sandywk 新版本应该解决这个问题了

**Comment by Luncher** [comment]
我先把问题关了
