### ISSUE TITLE
创建订单createOrder回调通知在哪可以配置?

### ISSUE THREAD

**Issue by lizhil** [Luncher/alipay#4]
能解答一下嘛!非常感谢

**Comment by lizhil** [comment]
@Luncher

**Comment by Luncher** [comment]
`createWebOrderURL` 你需要的应该是这个接口，网页支付的时候可以配置一个回调`URL`

**Comment by lizhil** [comment]
app支付接口无法创建回调URL嘛?我看官方文档是有一个notify_url参数

**Comment by Luncher** [comment]
可以在构造函数里面配置，

**Comment by Luncher** [comment]
@lizhil 文档更新了，有空再看看：）
