### ISSUE TITLE
Alipay is not a constructor

### ISSUE THREAD

**Issue by bookyo** [Luncher/alipay#49]
Alipay is not a constructor

const Alipay = require('alipay-mobile');
const options = {
    app_id: '***',
    appPrivKeyFile: read('./key/private-key.pem'),
    alipayPubKeyFile: read('./key/public-key.pem'),
    gatewayUrl: 'https://openapi.alipaydev.com/gateway.do'
}
const service = new Alipay(options);

开启应用提示 Alipay is not a constructor

版本3.0.9

**Comment by guoliping717** [comment]
我也遇到这情况了 不知道老兄你解决了吗

**Comment by xinlingqudongX** [comment]
const Alipay = require('alipay-mobile').default;
直接打印下或者调试就能看到的

**Comment by Luncher** [comment]
参考这个 issue https://github.com/microsoft/TypeScript/issues/2719，我改以下文档。
这个库我很久没有用了.. 谢谢反馈。
