### ISSUE TITLE
可以考虑增加电脑网站支付的接口

### ISSUE THREAD

**Issue by MaplerStory** [Luncher/alipay#5]
https://docs.open.alipay.com/270/105899/

alipay.trade.page.pay

**Comment by Luncher** [comment]
最近比较忙，没啥时间顾及这个了，欢迎提PR ：）

**Comment by mantou132** [comment]
好像只要改接口名称就好了吧

**Comment by Luncher** [comment]
周末的时候找个时间搞定这个事情：）
@MaplerStory @mantou132
