### ISSUE TITLE
文档能再详细点就好了，我是小白

### ISSUE THREAD

**Issue by zengleyi** [Luncher/alipay#8]
验证支付结果和异步验证校验需要传的参数具体是什么，全部必须传的参数有哪些？比如memo，result各是指什么？

**Comment by Luncher** [comment]
其实每个接口我都贴出来了相应的在线文档链接，如果我把这些东西都拷贝一份放到`README`的话，意味着我需要不定期的同步官方文档，所以没有这么做。另外也是希望使用的过程中最好还是稍微看看官方的文档，不需要太多，这样使用其实也比较顺手。
