### ISSUE TITLE
希望能再加一个资金API /  单笔转账到支付宝账户接口

### ISSUE THREAD

**Issue by zengleyi** [Luncher/alipay#9]
希望把这个功能加进去。原谅我伸手党了，es6来不及看。

**Comment by zengleyi** [comment]
支付宝官方文档在https://docs.open.alipay.com/api_28/alipay.fund.trans.toaccount.transfer/

**Comment by Luncher** [comment]
@zengleyi  好的，之前由于没有找到文档，抽空我把这个做一下，估计周三左右加好。

**Comment by zengleyi** [comment]
@Luncher 爱你！

**Comment by zengleyi** [comment]
哥们食言了吧，等的着急

**Comment by Luncher** [comment]
来了来了

**Comment by Luncher** [comment]
[#2](https://github.com/Luncher/alipay/issues/2)
